version: "3.9"

services:
  chickenfarm-logging:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  chickenfarm-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chickenfarm-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"

  chickenfarm-zipkin:
    image: openzipkin/zipkin-slim
    container_name: chickenfarm-zipkin
    ports:
      - "5411:9411"