version: "3.9"

services:
  chickenfarm-farmservice-api:
    image: jacobapps/chickenfarm-farmservice-api:dev
    container_name: chickenfarm-farmservice-api
    ports:
      - 81:81
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_FILE: src/FarmService/ChickenFarm.FarmService.Api/ChickenFarm.FarmService.Api.csproj
        PROJECT_DLL: ChickenFarm.FarmService.Api.dll
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:81"
      PATH_BASE: /chickenfarm-farmservice-api
      DatabaseSettings:Username: postgres
      DatabaseSettings:Password: postgres
      DatabaseSettings:Host: chickenfarm-db
      DatabaseSettings:Database: FarmServiceDatabase
    depends_on:
      - chickenfarm-db

