version: "3.9"

services:
  chickenfarm-frontend:
    image: jacobapps/chickenfarm-frontend:dev
    container_name: chickenfarm-frontend
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_FILE: src/FrontEnd/ChickenFarm.FrontEnd.Blazor/ChickenFarm.FrontEnd.Blazor.csproj
        PROJECT_DLL: ChickenFarm.FrontEnd.Blazor.dll
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:80"
      PATH_BASE: /chickenfarm-frontend

  chickenfarm-frontend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd",
               "-app-id", "chickenfarm-frontend",
               "-app-port", "80",
               "-components-path", "/components",
               "-config", "/configuration/config.yaml" ]
    network_mode: "service:chickenfarm-frontend"
    depends_on:
      - chickenfarm-frontend
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
