// <auto-generated />
using System;
using ChickenFarm.TaskService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ChickenFarm.TaskService.Infrastructure.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20210616101812_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ChickenFarm.Shared.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("Id");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("ChickenFarm.Shared.Shed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Sheds");
                });

            modelBuilder.Entity("ChickenFarm.Shared.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ShedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShedId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ChickenFarm.Shared.Shed", b =>
                {
                    b.HasOne("ChickenFarm.Shared.Farm", "Farm")
                        .WithMany("Sheds")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("ChickenFarm.Shared.Task", b =>
                {
                    b.HasOne("ChickenFarm.Shared.Shed", "Shed")
                        .WithMany("Tasks")
                        .HasForeignKey("ShedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shed");
                });

            modelBuilder.Entity("ChickenFarm.Shared.Farm", b =>
                {
                    b.Navigation("Sheds");
                });

            modelBuilder.Entity("ChickenFarm.Shared.Shed", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
